# Generated by Django 2.0.2 on 2018-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_todo_completed_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='high', max_length=10),
        ),
    ]
